// ============================================================
// MOCK DATABASE - Replace with API calls when backend is ready
// ============================================================

export const currentUser = {
  id: 1,
  name: "Admin User",
  email: "admin@erpsystem.com",
  avatar: "AU",
  role: "super_admin",
  permissions: ["all"],
};

export const users = [
  {
    id: 1,
    name: "Admin User",
    email: "admin@erpsystem.com",
    role: "super_admin",
    permissions: ["all"],
    avatar: "AU",
    status: "active",
  },
  {
    id: 2,
    name: "Rahim Uddin",
    email: "rahim@erpsystem.com",
    role: "manager",
    permissions: ["hotel", "inventory", "reporting"],
    avatar: "RU",
    status: "active",
  },
  {
    id: 3,
    name: "Karim Hossain",
    email: "karim@erpsystem.com",
    role: "hr_manager",
    permissions: ["hr", "payroll", "leave"],
    avatar: "KH",
    status: "active",
  },
  {
    id: 4,
    name: "Fatema Begum",
    email: "fatema@erpsystem.com",
    role: "accountant",
    permissions: ["accounting", "reporting"],
    avatar: "FB",
    status: "active",
  },
  {
    id: 5,
    name: "Salam Sheikh",
    email: "salam@erpsystem.com",
    role: "sales",
    permissions: ["sales", "inventory"],
    avatar: "SS",
    status: "inactive",
  },
];

export const modules = [
  {
    id: "hotel",
    name: "Hotel Management",
    namebn: "হোটেল ম্যানেজমেন্ট",
    icon: "🏨",
    color: "#6366f1",
    gradient: "from-indigo-500 to-purple-600",
    route: "/hotel",
    stats: { label: "Active Rooms", value: "128", change: "+12%" },
    description: "Room booking, guests, housekeeping & reservations",
    status: "active",
  },
  {
    id: "hospital",
    name: "Hospital Management",
    namebn: "হাসপাতাল ম্যানেজমেন্ট",
    icon: "🏥",
    color: "#ec4899",
    gradient: "from-pink-500 to-rose-600",
    route: "/hospital",
    stats: { label: "Patients Today", value: "47", change: "+8%" },
    description: "Patients, doctors, appointments & medical records",
    status: "active",
  },
  {
    id: "school",
    name: "School Management",
    namebn: "স্কুল ম্যানেজমেন্ট",
    icon: "🏫",
    color: "#f59e0b",
    gradient: "from-amber-500 to-orange-600",
    route: "/school",
    stats: { label: "Students", value: "1,240", change: "+3%" },
    description: "Students, teachers, classes & examination",
    status: "active",
  },
  {
    id: "accounting",
    name: "Accounting",
    namebn: "একাউন্টিং",
    icon: "📊",
    color: "#10b981",
    gradient: "from-emerald-500 to-teal-600",
    route: "/accounting",
    stats: { label: "Monthly Revenue", value: "৳4.2M", change: "+18%" },
    description: "Ledger, journal, balance sheet & P&L reports",
    status: "active",
  },
  {
    id: "inventory",
    name: "Inventory",
    namebn: "ইনভেন্টরি",
    icon: "📦",
    color: "#3b82f6",
    gradient: "from-blue-500 to-cyan-600",
    route: "/inventory",
    stats: { label: "Total Items", value: "3,847", change: "-2%" },
    description: "Products, categories, warehouses & tracking",
    status: "active",
  },
  {
    id: "hr",
    name: "HR Management",
    namebn: "এইচআর ম্যানেজমেন্ট",
    icon: "👥",
    color: "#8b5cf6",
    gradient: "from-violet-500 to-purple-600",
    route: "/hr",
    stats: { label: "Employees", value: "284", change: "+5%" },
    description: "Recruitment, employees, departments & performance",
    status: "active",
  },
  {
    id: "payroll",
    name: "Payroll / Salary",
    namebn: "পেরোল / বেতন",
    icon: "💰",
    color: "#f97316",
    gradient: "from-orange-500 to-amber-600",
    route: "/payroll",
    stats: { label: "This Month", value: "৳8.7M", change: "+2%" },
    description: "Salary processing, deductions & disbursement",
    status: "active",
  },
  {
    id: "leave",
    name: "Leave Management",
    namebn: "লিভ ম্যানেজমেন্ট",
    icon: "📅",
    color: "#06b6d4",
    gradient: "from-cyan-500 to-blue-600",
    route: "/leave",
    stats: { label: "Pending Requests", value: "12", change: "+4" },
    description: "Leave types, requests, approvals & calendar",
    status: "active",
  },
  {
    id: "stock",
    name: "Stock Management",
    namebn: "স্টক ম্যানেজমেন্ট",
    icon: "🏪",
    color: "#84cc16",
    gradient: "from-lime-500 to-green-600",
    route: "/stock",
    stats: { label: "Low Stock Items", value: "23", change: "-5" },
    description: "Stock levels, movements, alerts & reorder points",
    status: "active",
  },
  {
    id: "sales",
    name: "Sales Management",
    namebn: "সেলস ম্যানেজমেন্ট",
    icon: "📈",
    color: "#ef4444",
    gradient: "from-red-500 to-pink-600",
    route: "/sales",
    stats: { label: "Today's Sales", value: "৳142K", change: "+22%" },
    description: "Orders, customers, invoices & sales reports",
    status: "active",
  },
  {
    id: "purchase",
    name: "Purchase",
    namebn: "পার্চেজ",
    icon: "🛒",
    color: "#0ea5e9",
    gradient: "from-sky-500 to-blue-600",
    route: "/purchase",
    stats: { label: "Open POs", value: "18", change: "+3" },
    description: "Purchase orders, vendors, GRN & payments",
    status: "active",
  },
  {
    id: "reporting",
    name: "Reporting",
    namebn: "রিপোর্টিং",
    icon: "📋",
    color: "#a855f7",
    gradient: "from-purple-500 to-indigo-600",
    route: "/reporting",
    stats: { label: "Reports Generated", value: "94", change: "+14%" },
    description: "Custom reports, analytics & data export",
    status: "active",
  },
  {
    id: "user_management",
    name: "User Management",
    namebn: "ইউজার ম্যানেজমেন্ট",
    icon: "🔐",
    color: "#64748b",
    gradient: "from-slate-500 to-gray-600",
    route: "/users",
    stats: { label: "Active Users", value: "42", change: "+6" },
    description: "Users, roles, permissions & access control",
    status: "active",
  },
];

export const recentActivities = [
  {
    id: 1,
    module: "sales",
    action: "New order #INV-2024-0891 created",
    user: "Rahim Uddin",
    time: "2 min ago",
    type: "success",
  },
  {
    id: 2,
    module: "hr",
    action: "Leave approved for Karim Hossain",
    user: "Admin",
    time: "15 min ago",
    type: "info",
  },
  {
    id: 3,
    module: "inventory",
    action: "Stock alert: Rice (50kg) below reorder",
    user: "System",
    time: "32 min ago",
    type: "warning",
  },
  {
    id: 4,
    module: "payroll",
    action: "Salary disbursed for March 2024",
    user: "Admin",
    time: "1 hr ago",
    type: "success",
  },
  {
    id: 5,
    module: "hotel",
    action: "Room 204 checked out - Jamal Ahmed",
    user: "Front Desk",
    time: "2 hr ago",
    type: "info",
  },
  {
    id: 6,
    module: "accounting",
    action: "Journal entry #JE-00234 posted",
    user: "Fatema Begum",
    time: "3 hr ago",
    type: "success",
  },
];

export const kpiData = {
  revenue: {
    value: "৳12.4M",
    change: "+18.5%",
    trend: "up",
    label: "Total Revenue",
  },
  expenses: {
    value: "৳8.1M",
    change: "+6.2%",
    trend: "up",
    label: "Total Expenses",
  },
  profit: {
    value: "৳4.3M",
    change: "+34.1%",
    trend: "up",
    label: "Net Profit",
  },
  employees: {
    value: "284",
    change: "+12",
    trend: "up",
    label: "Total Employees",
  },
};

export const chartData = [
  { month: "Jan", revenue: 8500000, expense: 5200000 },
  { month: "Feb", revenue: 9200000, expense: 5800000 },
  { month: "Mar", revenue: 8800000, expense: 5500000 },
  { month: "Apr", revenue: 10200000, expense: 6200000 },
  { month: "May", revenue: 11500000, expense: 7100000 },
  { month: "Jun", revenue: 10800000, expense: 6800000 },
  { month: "Jul", revenue: 12400000, expense: 8100000 },
];

export const rolePermissions = {
  super_admin: ["all"],
  manager: ["hotel", "inventory", "reporting", "sales"],
  hr_manager: ["hr", "payroll", "leave", "reporting"],
  accountant: ["accounting", "reporting"],
  sales: ["sales", "inventory"],
};
